name: "Enforce data-migration label"
on:
  pull_request_target:
    types: [unlabeled]

jobs:
  enforce_labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: marcocarvalho/get-user-teams-membership@v2
      id: checkUserMember
      with:
        username: ${{ github.event.sender.login }}
        GITHUB_TOKEN: ${{ secrets.CO1_AUTO_APPROVE_TOKEN }} # needs org:read permission
    - uses: actions/labeler@v4
      if: ${{ github.event.label.name == 'data migration' && !contains(steps.checkUserMember.outputs.teams, 'test-team') }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
